<?php
include("../modelo/modelo_articulos.php");
$articulos=getlistaArticulos();
if(isset($_GET["cod_art"])){
    $codigo=$_GET['cod_art'];
    $articulos="";
    if($codigo!=0){
        $articulos=getArticulo($codigo);
    }else{
        $articulos=getlistaArticulos();
    }
	include("../vista/articulos.php");
}
